name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.NEKOCHANS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.NEKOCHANS_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.8

    - name: Terraform Format
      run: terraform fmt -recursive -check

    - name: Terraform stg/10-acm
      working-directory: ./providers/aws/environments/stg/10-acm
      run: |
        terraform init
        terraform validate
        terraform plan

    - name: Terraform stg/20-frontend
      working-directory: ./providers/aws/environments/stg/20-frontend
      run: |
        terraform init
        terraform validate
        terraform plan

    - name: Terraform prod/10-acm
      working-directory: ./providers/aws/environments/prod/10-acm
      run: |
        terraform init
        terraform validate
        terraform plan

    - name: Terraform prod/10-github
      working-directory: ./providers/aws/environments/prod/10-github
      run: |
        terraform init
        terraform validate
        terraform plan

    - name: Terraform prod/20-frontend
      working-directory: ./providers/aws/environments/prod/20-frontend
      run: |
        terraform init
        terraform validate
        terraform plan
